package com.securityanalyzer.service;

import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import com.securityanalyzer.entity.*;
import org.springframework.stereotype.Service;

import java.awt.Color;
import java.io.OutputStream;
import java.time.format.DateTimeFormatter;

@Service
public class PdfReportServiceImpl implements PdfReportService {

    private static final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    @Override
    public void generateScanReport(ScanHistory scan, OutputStream os) {
        Document document = new Document(PageSize.A4, 36, 36, 54, 36);
        try {
            PdfWriter.getInstance(document, os);
            document.open();

            // Fonts definitions
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 22, new Color(15, 23, 42));
            Font subtitleFont = FontFactory.getFont(FontFactory.HELVETICA, 10, new Color(100, 116, 139));
            Font sectionHeaderFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, new Color(30, 41, 59));
            Font normalFont = FontFactory.getFont(FontFactory.HELVETICA, 10, new Color(15, 23, 42));
            Font boldFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, new Color(15, 23, 42));
            Font smallFont = FontFactory.getFont(FontFactory.HELVETICA, 8, new Color(100, 116, 139));

            // Document Header
            Paragraph title = new Paragraph("WEBSITE SECURITY INSPECTION REPORT", titleFont);
            title.setSpacingAfter(4);
            document.add(title);

            Paragraph subtitle = new Paragraph("Generated by Antigravity Shield Security Suite  |  Date: " + 
                    (scan.getCompletedAt() != null ? scan.getCompletedAt().format(formatter) : scan.getCreatedAt().format(formatter)), subtitleFont);
            subtitle.setSpacingAfter(15);
            document.add(subtitle);

            // Add Divider Line
            Paragraph divider = new Paragraph("----------------------------------------------------------------------------------------------------------------------------------", smallFont);
            divider.setSpacingAfter(15);
            document.add(divider);

            // Overview Section
            Paragraph secHeader1 = new Paragraph("1. Inspection Summary & Target Information", sectionHeaderFont);
            secHeader1.setSpacingAfter(10);
            document.add(secHeader1);

            // Info Table
            PdfPTable infoTable = new PdfPTable(2);
            infoTable.setWidthPercentage(100);
            infoTable.setSpacingAfter(15);

            addTableCell(infoTable, "Target Website URL", boldFont);
            addTableCell(infoTable, scan.getTargetUrl(), normalFont);

            addTableCell(infoTable, "Response Connection Time", boldFont);
            addTableCell(infoTable, scan.getResponseTimeMs() != null ? scan.getResponseTimeMs() + " ms" : "N/A", normalFont);

            addTableCell(infoTable, "Redirect Hops Count", boldFont);
            addTableCell(infoTable, String.valueOf(scan.getRedirectCount()), normalFont);

            addTableCell(infoTable, "Execution Audit Status", boldFont);
            addTableCell(infoTable, scan.getStatus(), normalFont);

            document.add(infoTable);

            // Safety Score Banner Card
            Color scoreBgColor = new Color(239, 68, 68); // Red
            Color scoreTextColor = Color.WHITE;
            if (scan.getScore() >= 80) {
                scoreBgColor = new Color(16, 185, 129); // Green
            } else if (scan.getScore() >= 55) {
                scoreBgColor = new Color(245, 158, 11); // Warning Orange
            }

            PdfPTable scoreTable = new PdfPTable(1);
            scoreTable.setWidthPercentage(100);
            scoreTable.setSpacingAfter(25);

            PdfPCell scoreCell = new PdfPCell(new Phrase("OVERALL WEBSITE SAFETY INDEX: " + scan.getScore() + " / 100", 
                    FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, scoreTextColor)));
            scoreCell.setBackgroundColor(scoreBgColor);
            scoreCell.setPadding(12);
            scoreCell.setHorizontalAlignment(Element.ALIGN_CENTER);
            scoreCell.setBorder(Rectangle.NO_BORDER);
            scoreTable.addCell(scoreCell);
            document.add(scoreTable);

            // Security Recommendations & Failed Checks Section
            Paragraph secHeaderRec = new Paragraph("2. Action Items & Security Recommendations", sectionHeaderFont);
            secHeaderRec.setSpacingAfter(10);
            document.add(secHeaderRec);

            if (scan.getRecommendations() == null || scan.getRecommendations().isEmpty()) {
                Paragraph noRecs = new Paragraph("No security vulnerabilities were detected on this target. Excellent!", normalFont);
                noRecs.setSpacingAfter(20);
                document.add(noRecs);
            } else {
                for (ScanRecommendation rec : scan.getRecommendations()) {
                    Paragraph bullet = new Paragraph();
                    bullet.add(new Chunk("[" + rec.getCategory() + "]  " + rec.getCheckName() + ": ", boldFont));
                    bullet.add(new Chunk(rec.getRecommendation(), normalFont));
                    bullet.setSpacingAfter(8);
                    bullet.setIndentationLeft(15);
                    document.add(bullet);
                }
                Paragraph spacing = new Paragraph(" ");
                spacing.setSpacingAfter(10);
                document.add(spacing);
            }

            // SSL certificate details Section
            Paragraph secHeaderSsl = new Paragraph("3. SSL/TLS Certificate Specification", sectionHeaderFont);
            secHeaderSsl.setSpacingAfter(10);
            document.add(secHeaderSsl);

            SSLInfo ssl = scan.getSslInfo();
            if (ssl != null && ssl.isSslEnabled()) {
                PdfPTable sslTable = new PdfPTable(2);
                sslTable.setWidthPercentage(100);
                sslTable.setSpacingAfter(20);

                addTableCell(sslTable, "SSL Enabled", boldFont);
                addTableCell(sslTable, "Yes" + (ssl.isExpired() ? " (EXPIRED)" : " (ACTIVE)"), normalFont);

                addTableCell(sslTable, "Protocol Handshake", boldFont);
                addTableCell(sslTable, ssl.getProtocol() != null ? ssl.getProtocol() : "N/A", normalFont);

                addTableCell(sslTable, "Cipher Suite", boldFont);
                addTableCell(sslTable, ssl.getCipherSuite() != null ? ssl.getCipherSuite() : "N/A", normalFont);

                addTableCell(sslTable, "Certificate Authority", boldFont);
                addTableCell(sslTable, ssl.getIssuer() != null ? ssl.getIssuer() : "N/A", normalFont);

                addTableCell(sslTable, "Valid From Scope", boldFont);
                addTableCell(sslTable, ssl.getValidFrom() != null ? ssl.getValidFrom().format(formatter) : "N/A", normalFont);

                addTableCell(sslTable, "Valid Until Scope", boldFont);
                addTableCell(sslTable, ssl.getValidTo() != null ? ssl.getValidTo().format(formatter) : "N/A", normalFont);

                document.add(sslTable);
            } else {
                Paragraph noSsl = new Paragraph("Insecure connections. SSL/TLS certificate was not resolved. Plaintext communication is active.", normalFont);
                noSsl.setSpacingAfter(20);
                document.add(noSsl);
            }

            // Security headers section
            Paragraph secHeaderH = new Paragraph("4. HTTP Security Headers Audit", sectionHeaderFont);
            secHeaderH.setSpacingAfter(10);
            document.add(secHeaderH);

            if (scan.getSecurityHeaders() != null && !scan.getSecurityHeaders().isEmpty()) {
                PdfPTable headerTable = new PdfPTable(3);
                headerTable.setWidthPercentage(100);
                headerTable.setSpacingAfter(20);
                headerTable.setWidths(new float[]{30, 20, 50});

                addTableHeaderCell(headerTable, "Security Header Key", boldFont);
                addTableHeaderCell(headerTable, "Status", boldFont);
                addTableHeaderCell(headerTable, "Rating", boldFont);

                for (SecurityHeader h : scan.getSecurityHeaders()) {
                    addTableCell(headerTable, h.getHeaderName(), normalFont);
                    addTableCell(headerTable, h.isPresent() ? "Present" : "Missing", normalFont);
                    addTableCell(headerTable, h.getSecurityRating(), normalFont);
                }
                document.add(headerTable);
            } else {
                Paragraph noHeaders = new Paragraph("No security header audits loaded.", normalFont);
                noHeaders.setSpacingAfter(20);
                document.add(noHeaders);
            }

            // Cookie analysis section
            Paragraph secHeaderC = new Paragraph("5. Transmitted Cookie Analysis", sectionHeaderFont);
            secHeaderC.setSpacingAfter(10);
            document.add(secHeaderC);

            if (scan.getCookieAnalyses() != null && !scan.getCookieAnalyses().isEmpty()) {
                PdfPTable cookieTable = new PdfPTable(4);
                cookieTable.setWidthPercentage(100);
                cookieTable.setSpacingAfter(20);
                cookieTable.setWidths(new float[]{40, 20, 20, 20});

                addTableHeaderCell(cookieTable, "Cookie Key Name", boldFont);
                addTableHeaderCell(cookieTable, "Secure Flag", boldFont);
                addTableHeaderCell(cookieTable, "HttpOnly Flag", boldFont);
                addTableHeaderCell(cookieTable, "SameSite Flag", boldFont);

                for (CookieAnalysis c : scan.getCookieAnalyses()) {
                    addTableCell(cookieTable, c.getCookieName(), normalFont);
                    addTableCell(cookieTable, c.isSecure() ? "Yes" : "No", normalFont);
                    addTableCell(cookieTable, c.isHttpOnly() ? "Yes" : "No", normalFont);
                    addTableCell(cookieTable, c.getSameSite() != null ? c.getSameSite() : "None", normalFont);
                }
                document.add(cookieTable);
            } else {
                Paragraph noCookies = new Paragraph("No Set-Cookie parameters found in target HTTP response headers.", normalFont);
                noCookies.setSpacingAfter(20);
                document.add(noCookies);
            }

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            document.close();
        }
    }

    private void addTableCell(PdfPTable table, String text, Font font) {
        PdfPCell cell = new PdfPCell(new Phrase(text, font));
        cell.setPadding(6);
        cell.setBorderColor(new Color(226, 232, 240));
        table.addCell(cell);
    }

    private void addTableHeaderCell(PdfPTable table, String text, Font font) {
        PdfPCell cell = new PdfPCell(new Phrase(text, font));
        cell.setPadding(8);
        cell.setBackgroundColor(new Color(241, 245, 249));
        cell.setBorderColor(new Color(226, 232, 240));
        table.addCell(cell);
    }
}
